# bin2header.cmake -- embed a binary file as a C array header.
# Usage: cmake -DINPUT_FILE=<bin> -DOUTPUT_FILE=<header> -DARRAY_NAME=<name> -P bin2header.cmake

if(NOT DEFINED INPUT_FILE OR NOT DEFINED OUTPUT_FILE OR NOT DEFINED ARRAY_NAME)
    message(FATAL_ERROR "bin2header.cmake: INPUT_FILE, OUTPUT_FILE and ARRAY_NAME must be defined")
endif()

file(READ "${INPUT_FILE}" _hex HEX)
string(LENGTH "${_hex}" _hex_len)
math(EXPR _byte_size "${_hex_len} / 2")
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _array "${_hex}")

file(WRITE "${OUTPUT_FILE}"
"// Generated by bin2header.cmake from ${INPUT_FILE} -- do not edit.
static const unsigned char ${ARRAY_NAME}[] = {${_array}};
static const unsigned int ${ARRAY_NAME}_size = ${_byte_size};
")
