name: Release

on:
  release:
    types:
      - published

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  ce-dat:
    name: Build ce.dat
    uses: ./.github/workflows/reusable-build-ce-dat.yml
    with:
      preset: linux-x64-release

  android:
    name: Android

    runs-on: ubuntu-latest
    needs: [ce-dat]
    permissions:
      contents: write

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: gradle

      - name: Cache cmake build
        uses: actions/cache@v4
        with:
          path: os/android/app/.cxx
          key: android-cmake-v1

      - name: Setup signing config
        if: env.KEYSTORE_FILE_BASE64 != '' && env.KEYSTORE_PROPERTIES_FILE_BASE64 != ''
        run: |
          cd os/android
          echo "$KEYSTORE_FILE_BASE64" | base64 --decode > release.keystore
          echo "$KEYSTORE_PROPERTIES_FILE_BASE64" | base64 --decode > release-keystore.properties
        env:
          KEYSTORE_FILE_BASE64: ${{ secrets.ANDROID_RELEASE_KEYSTORE_FILE_BASE64 }}
          KEYSTORE_PROPERTIES_FILE_BASE64: ${{ secrets.ANDROID_RELEASE_KEYSTORE_PROPERTIES_FILE_BASE64 }}

      - name: Build
        run: |
          cd os/android
          ./gradlew assembleRelease

      - name: Download ce.dat
        uses: actions/download-artifact@v4
        with:
          name: ce-dat
          path: out/dist

      - name: Upload
        run: |
          mkdir -p out/dist/fallout2-ce-android
          cp os/android/app/build/outputs/apk/release/app-release.apk out/dist/fallout2-ce-android/fallout2-ce-android.apk
          cp out/dist/ce.dat out/dist/fallout2-ce-android/ce.dat
          cp files/fallout2.cfg out/dist/fallout2-ce-android/EXAMPLE_fallout2.cfg
          cd out/dist
          zip -r fallout2-ce-android.zip fallout2-ce-android
          gh release upload ${{ github.event.release.tag_name }} fallout2-ce-android.zip
          rm fallout2-ce-android.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ios:
    name: iOS

    runs-on: macos-14
    needs: [ce-dat]
    permissions:
      contents: write

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Cache cmake build
        uses: actions/cache@v4
        with:
          path: build
          key: ios-cmake-v1

      - name: Configure
        run: |
          cmake \
            -B build \
            -D CMAKE_TOOLCHAIN_FILE=cmake/toolchain/ios.toolchain.cmake \
            -D ENABLE_BITCODE=0 \
            -D PLATFORM=OS64 \
            -G Xcode \
            -D CMAKE_XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY='' \
            # EOL

      - name: Build
        run: |
          cmake \
            --build build \
            --config RelWithDebInfo \
            -j $(sysctl -n hw.physicalcpu) \
            # EOL

      - name: Pack
        run: |
          cd build
          cpack -C RelWithDebInfo

      - name: Download ce.dat
        uses: actions/download-artifact@v4
        with:
          name: ce-dat
          path: out/dist

      - name: Upload
        run: |
          mkdir -p out/dist/fallout2-ce-ios
          cp build/fallout2-ce.ipa out/dist/fallout2-ce-ios/fallout2-ce-ios.ipa
          cp out/dist/ce.dat out/dist/fallout2-ce-ios/ce.dat
          cp files/fallout2.cfg out/dist/fallout2-ce-ios/EXAMPLE_fallout2.cfg
          cd out/dist
          zip -r fallout2-ce-ios.zip fallout2-ce-ios
          gh release upload ${{ github.event.release.tag_name }} fallout2-ce-ios.zip
          rm fallout2-ce-ios.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  linux:
    name: Linux (${{ matrix.arch }})

    runs-on: ubuntu-20.04
    needs: [ce-dat]
    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86
          - x64

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Dependencies (x86)
        if: matrix.arch == 'x86'
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install --allow-downgrades libpcre2-8-0=10.34-7
          sudo apt install g++-multilib libsdl2-dev:i386 zlib1g-dev:i386

      - name: Dependencies (x64)
        if: matrix.arch == 'x64'
        run: |
          sudo apt update
          sudo apt install libsdl2-dev zlib1g-dev

      - name: Cache cmake build
        uses: actions/cache@v4
        with:
          path: build
          key: linux-${{ matrix.arch }}-cmake-v1

      - name: Configure (x86)
        if: matrix.arch == 'x86'
        run: |
          cmake \
            -B build \
            -D CMAKE_BUILD_TYPE=RelWithDebInfo \
            -D CMAKE_TOOLCHAIN_FILE=cmake/toolchain/Linux32.cmake \
            # EOL

      - name: Configure (x64)
        if: matrix.arch == 'x64'
        run: |
          cmake \
            -B build \
            -D CMAKE_BUILD_TYPE=RelWithDebInfo \
            # EOL

      - name: Build
        run: |
          cmake \
            --build build \
            -j $(nproc) \
            # EOL

      - name: Download ce.dat
        uses: actions/download-artifact@v4
        with:
          name: ce-dat
          path: out/dist

      - name: Upload
        run: |
          mkdir -p out/dist/fallout2-ce-linux-${{ matrix.arch }}
          cp build/fallout2-ce out/dist/fallout2-ce-linux-${{ matrix.arch }}/fallout2-ce
          cp out/dist/ce.dat out/dist/fallout2-ce-linux-${{ matrix.arch }}/ce.dat
          cp files/fallout2.cfg out/dist/fallout2-ce-linux-${{ matrix.arch }}/EXAMPLE_fallout2.cfg
          tar -czvf fallout2-ce-linux-${{ matrix.arch }}.tar.gz -C out/dist fallout2-ce-linux-${{ matrix.arch }}
          gh release upload ${{ github.event.release.tag_name }} fallout2-ce-linux-${{ matrix.arch }}.tar.gz
          rm fallout2-ce-linux-${{ matrix.arch }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  macos:
    name: macOS

    runs-on: macos-11
    permissions:
      contents: write

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Import code signing certificates
        uses: apple-actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_P12_FILE_BASE64 }}
          p12-password: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_P12_PASSWORD }}

      - name: Cache cmake build
        uses: actions/cache@v4
        with:
          path: build
          key: macos-cmake-v3

      - name: Configure
        run: |
          cmake \
            -B build \
            -G Xcode \
            -D CMAKE_XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY="${{ secrets.APPLE_DEVELOPER_CERTIFICATE_IDENTITY }}" \
            -D CMAKE_XCODE_ATTRIBUTE_CODE_SIGN_INJECT_BASE_ENTITLEMENTS="NO" \
            -D CMAKE_XCODE_ATTRIBUTE_OTHER_CODE_SIGN_FLAGS="--options=runtime --timestamp" \
            # EOL

      - name: Build
        run: |
          cmake \
            --build build \
            --config RelWithDebInfo \
            -j $(sysctl -n hw.physicalcpu) \
            # EOL

      - name: Pack
        run: |
          cd build
          cpack -C RelWithDebInfo

      - name: Notarize
        run: |
          xcrun notarytool submit \
            "build/Fallout II Community Edition.dmg" \
            --apple-id "${{ secrets.APPLE_DEVELOPER_AC_USERNAME }}" \
            --team-id "${{ secrets.APPLE_DEVELOPER_AC_TEAM }}" \
            --password "${{ secrets.APPLE_DEVELOPER_AC_PASSWORD }}" \
            --wait

      - name: Staple
        run: |
          xcrun stapler staple \
            "build/Fallout II Community Edition.dmg"

      - name: Upload
        run: |
          cd build
          cp "Fallout II Community Edition.dmg" fallout2-ce-macos.dmg
          gh release upload ${{ github.event.release.tag_name }} fallout2-ce-macos.dmg
          rm fallout2-ce-macos.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  windows:
    name: Windows (${{ matrix.arch }})

    runs-on: windows-2025
    needs: [ce-dat]
    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86
          - arch: x64

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Install Visual Studio 2022 Build Tools with v141_xp
        shell: cmd
        run: |
          choco install visualstudio2022buildtools -y --package-parameters="'--add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.Component.VC.v141.x86.x64 --add Microsoft.VisualStudio.Component.VC.v141.xp --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.Windows10SDK.10240 --add Microsoft.VisualStudio.ComponentGroup.NativeDesktop.WinXP --add Microsoft.VisualStudio.Component.WinXP'"

      - name: Cache cmake build
        uses: actions/cache@v4
        with:
          path: out
          key: windows-${{ matrix.arch }}-cmake-v2

      - name: Configure
        shell: cmd
        run: |
          for /f "usebackq tokens=*" %%i in (`"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products Microsoft.VisualStudio.Product.BuildTools -requires Microsoft.VisualStudio.Component.VC.v141.x86.x64 Microsoft.VisualStudio.Component.VC.v141.xp -property installationPath`) do set "VS_PATH=%%i"
          call "%VS_PATH%\Common7\Tools\VsDevCmd.bat" ^
          && cmake --preset windows-${{ matrix.arch }}

      - name: Build
        shell: cmd
        run: |
          for /f "usebackq tokens=*" %%i in (`"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products Microsoft.VisualStudio.Product.BuildTools -requires Microsoft.VisualStudio.Component.VC.v141.x86.x64 Microsoft.VisualStudio.Component.VC.v141.xp -property installationPath`) do set "VS_PATH=%%i"
          call "%VS_PATH%\Common7\Tools\VsDevCmd.bat" ^
          && cmake --build --preset windows-${{ matrix.arch }}-release

      - name: Download ce.dat
        uses: actions/download-artifact@v4
        with:
          name: ce-dat
          path: out/dist

      - name: Upload
        run: |
          mkdir -p out/dist/fallout2-ce-windows-${{ matrix.arch }}
          cp out/build/windows-${{ matrix.arch }}/RelWithDebInfo/fallout2coop.exe out/dist/fallout2-ce-windows-${{ matrix.arch }}/fallout2coop.exe
          cp out/dist/ce.dat out/dist/fallout2-ce-windows-${{ matrix.arch }}/ce.dat
          cp files/fallout2.cfg out/dist/fallout2-ce-windows-${{ matrix.arch }}/EXAMPLE_fallout2.cfg
          cd out/dist
          7z a fallout2-ce-windows-${{ matrix.arch }}.zip fallout2-ce-windows-${{ matrix.arch }}
          gh release upload ${{ github.event.release.tag_name }} fallout2-ce-windows-${{ matrix.arch }}.zip
          rm fallout2-ce-windows-${{ matrix.arch }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
